version: "3"
networks:
  my-net:
    driver: bridge
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - $PWD/zookeeper-data:/bitnami/zookeeper
    networks:
      - my-net
  kafka:
    image: 'bitnami/kafka:latest'
    restart: "always"
    ports:
      - "9092:9092"
      - "29092:29092"
      - "39092:39092"
    environment:
      KAFKA_ENABLE_KRAFT: no
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "CLIENT"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT,FOREIGN:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "CLIENT://:9092,EXTERNAL://:29092,FOREIGN://:39092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://kafka:9092,EXTERNAL://localhost:29092,FOREIGN://${MACHINE_IP}:39092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      BITNAMI_DEBUG: "true"
    volumes:
      - $PWD/kafka-logs:/bitnami/kafka
    networks:
      - my-net
    depends_on:
      - "zookeeper"
  kafdrop:
    # https://github.com/obsidiandynamics/kafdrop
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
      - my-net
    depends_on:
      - "kafka"
  connect:
    image: xchenhao/kafka-connect:0.1.0
    build:
      context: kafka-connect
      args:
        DEBEZIUM_VERSION: 2.1
    restart: "always"
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "my_connect_configs"
      OFFSET_STORAGE_TOPIC: "my_connect_offsets"
      STATUS_STORAGE_TOPIC: "my_connect_statuses"
      BOOTSTRAP_SERVERS: "${MACHINE_IP}:39092"
    networks:
      - my-net
    depends_on:
      - "kafka"
